### PR TITLE
Code of conduct.md

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
issue #3

### CODE REVIEW

**Comment by Brijeshthummar02** [comment]
Share feedback for current pull request, and if it's fine than please do me a favor merge it in oct 1-2 when hacktoberfest starts so that i can claim merge request.

**Comment by shubhansu-kr** [comment]
@Brijeshthummar02 This is not the right way. I appreciate your enthusiasm and passion to contribute to open source, but you were not assigned this issue in the first place. Please request assignee on the issue you want to work on and then create a PR. Please avoid creating conflicts.

**Comment by shubhansu-kr** [comment]
Additionally, You are required to create PR between 1st oct to 30st oct to get accepted for hactoberfest. If you create it today and merge it later, it won't work.

**Comment by Brijeshthummar02** [comment]
@shubhansu-kr i totally agree on that, but you commented 3 days ago and still not created a pr, so i thought why not i. 
as of now i've created a pr so you can work on some other issues.

**Comment by shubhansu-kr** [comment]
> @shubhansu-kr i totally agree on that, but you commented 3 days ago and still not created a pr, so i thought why not i. as of now i've created a pr so you can work on some other issues.

Your "why not" should be answered by "Because it's not assigned to me". I hope that helps.

**Comment by Brijeshthummar02** [comment]
You taking it personally.

**Comment by shubhansu-kr** [comment]
I have my PR ready, but didn't create one because it should adhere to the hactoberfest timelines. This PR you created is invalid and should be marked accordingly. However that decision is upto the project maintainer to make. 

Thanks.

**Comment by shubhansu-kr** [comment]
> You taking it personally.

I am following the guidelines.

**Comment by DhanushNehru** [comment]
Hi @Brijeshthummar02  please check issue section first before raising a PR.

This issue is already assigned to @shubhansu-kr 

But @shubhansu-kr it's over to you to decide whether I should close this PR or Merge it ?

**Comment by shubhansu-kr** [comment]
@DhanushNehru, appreciate your guidance. I won't have had any issue merging this PR, however i notice, @Brijeshthummar02 has done similar thing with other issues as well as you can see here #2 . 
This does not foster collaboration and leads to waste of community efforts given i have my branch ready, just waiting for hactoberfest to start. 

I leave this decision upto you, it's fine both ways if he stops doing this with other issues as well. 

Thanks.

**Comment by Brijeshthummar02** [comment]
@shubhansu-kr i got it, won't be doing it again.

**Comment by DhanushNehru** [comment]
Closing this PR as the issue is already assigned to @shubhansu-kr

**Comment by Brijeshthummar02** [comment]
@DhanushNehru as you can see it's already 2nd of october and @shubhansu-kr has not raised pr, and closed my pr.
 
i request you assign me again the task.

**Comment by shubhansu-kr** [comment]
Thanks for your concern @Brijeshthummar02,

But i have already raised the PR and it's already merged. Please don't take
it personally.

Happy contributing

**Pull request closed without merging**
