### PR TITLE
updated the security.md file

### PR DESCRIPTION
**Pull request by Raushan-Shahi**
I have updated the security.md file. 
Added the link to Discord for queries and an address time of 10 days.

### CODE REVIEW

**Comment by DhanushNehru** [comment]
@Raushan-Shahi please mention the issue number

**Comment by shubhansu-kr** [comment]
Issue #2

**Review by DhanushNehru — APPROVED** [review]

**Comment by DhanushNehru** [comment]
Closes #2

**Comment by shubhansu-kr** [comment]
@DhanushNehru I am confused, was this PR merged or Cancelled. I dont see changes in mainline

**Pull request closed without merging**
